package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/data/alicemap.oep", "assets/data/alicemap.oep");
			type.set ("assets/data/alicemap.oep", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/maze.oel", "assets/data/maze.oel");
			type.set ("assets/data/maze.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/plats.oel", "assets/data/plats.oel");
			type.set ("assets/data/plats.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/rtgmap.oep", "assets/data/rtgmap.oep");
			type.set ("assets/data/rtgmap.oep", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/fonts/OratorStd.otf", "assets/fonts/OratorStd.otf");
			type.set ("assets/fonts/OratorStd.otf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/images/about/stemlogo.pdn", "assets/images/about/stemlogo.pdn");
			type.set ("assets/images/about/stemlogo.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/about/stemlogo.png", "assets/images/about/stemlogo.png");
			type.set ("assets/images/about/stemlogo.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/about/title_about.png", "assets/images/about/title_about.png");
			type.set ("assets/images/about/title_about.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/alice_hit.png", "assets/images/alicemaze/alice_hit.png");
			type.set ("assets/images/alicemaze/alice_hit.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-bottom.png", "assets/images/alicemaze/b-bottom.png");
			type.set ("assets/images/alicemaze/b-bottom.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-full.png", "assets/images/alicemaze/b-full.png");
			type.set ("assets/images/alicemaze/b-full.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-hori.png", "assets/images/alicemaze/b-hori.png");
			type.set ("assets/images/alicemaze/b-hori.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-island.png", "assets/images/alicemaze/b-island.png");
			type.set ("assets/images/alicemaze/b-island.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-lb.png", "assets/images/alicemaze/b-lb.png");
			type.set ("assets/images/alicemaze/b-lb.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-left.png", "assets/images/alicemaze/b-left.png");
			type.set ("assets/images/alicemaze/b-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-map.png", "assets/images/alicemaze/b-map.png");
			type.set ("assets/images/alicemaze/b-map.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-rb.png", "assets/images/alicemaze/b-rb.png");
			type.set ("assets/images/alicemaze/b-rb.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-right.png", "assets/images/alicemaze/b-right.png");
			type.set ("assets/images/alicemaze/b-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-top.png", "assets/images/alicemaze/b-top.png");
			type.set ("assets/images/alicemaze/b-top.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-ul.png", "assets/images/alicemaze/b-ul.png");
			type.set ("assets/images/alicemaze/b-ul.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-ur.png", "assets/images/alicemaze/b-ur.png");
			type.set ("assets/images/alicemaze/b-ur.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/b-vert.png", "assets/images/alicemaze/b-vert.png");
			type.set ("assets/images/alicemaze/b-vert.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/cleaner.png", "assets/images/alicemaze/cleaner.png");
			type.set ("assets/images/alicemaze/cleaner.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/alice_dialogue_back.pdn", "assets/images/alicemaze/dialogue/alice_dialogue_back.pdn");
			type.set ("assets/images/alicemaze/dialogue/alice_dialogue_back.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/alice_dialogue_back.png", "assets/images/alicemaze/dialogue/alice_dialogue_back.png");
			type.set ("assets/images/alicemaze/dialogue/alice_dialogue_back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/OldManNormal.png", "assets/images/alicemaze/dialogue/OldManNormal.png");
			type.set ("assets/images/alicemaze/dialogue/OldManNormal.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/speak0.png", "assets/images/alicemaze/dialogue/speak0.png");
			type.set ("assets/images/alicemaze/dialogue/speak0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/speak_0.png", "assets/images/alicemaze/dialogue/speak_0.png");
			type.set ("assets/images/alicemaze/dialogue/speak_0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/speak_template.png", "assets/images/alicemaze/dialogue/speak_template.png");
			type.set ("assets/images/alicemaze/dialogue/speak_template.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/tag.png", "assets/images/alicemaze/dialogue/tag.png");
			type.set ("assets/images/alicemaze/dialogue/tag.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/wasd/wasd_a.png", "assets/images/alicemaze/dialogue/wasd/wasd_a.png");
			type.set ("assets/images/alicemaze/dialogue/wasd/wasd_a.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/wasd/wasd_d.png", "assets/images/alicemaze/dialogue/wasd/wasd_d.png");
			type.set ("assets/images/alicemaze/dialogue/wasd/wasd_d.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/wasd/wasd_finger.pdn", "assets/images/alicemaze/dialogue/wasd/wasd_finger.pdn");
			type.set ("assets/images/alicemaze/dialogue/wasd/wasd_finger.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/wasd/wasd_s.pdn", "assets/images/alicemaze/dialogue/wasd/wasd_s.pdn");
			type.set ("assets/images/alicemaze/dialogue/wasd/wasd_s.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/wasd/wasd_s.png", "assets/images/alicemaze/dialogue/wasd/wasd_s.png");
			type.set ("assets/images/alicemaze/dialogue/wasd/wasd_s.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/wasd/wasd_template.pdn", "assets/images/alicemaze/dialogue/wasd/wasd_template.pdn");
			type.set ("assets/images/alicemaze/dialogue/wasd/wasd_template.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/wasd/wasd_w.png", "assets/images/alicemaze/dialogue/wasd/wasd_w.png");
			type.set ("assets/images/alicemaze/dialogue/wasd/wasd_w.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/dialogue/wasd.png", "assets/images/alicemaze/dialogue/wasd.png");
			type.set ("assets/images/alicemaze/dialogue/wasd.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/alicemaze/player.png", "assets/images/alicemaze/player.png");
			type.set ("assets/images/alicemaze/player.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/bt_orig/comp_alice_alt.png", "assets/images/component/bt_orig/comp_alice_alt.png");
			type.set ("assets/images/component/bt_orig/comp_alice_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/bt_orig/comp_alice_hover.png", "assets/images/component/bt_orig/comp_alice_hover.png");
			type.set ("assets/images/component/bt_orig/comp_alice_hover.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/bt_orig/comp_lorri_alt.png", "assets/images/component/bt_orig/comp_lorri_alt.png");
			type.set ("assets/images/component/bt_orig/comp_lorri_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/bt_orig/comp_lorri_hover.png", "assets/images/component/bt_orig/comp_lorri_hover.png");
			type.set ("assets/images/component/bt_orig/comp_lorri_hover.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/bt_orig/comp_pepssi_alt.png", "assets/images/component/bt_orig/comp_pepssi_alt.png");
			type.set ("assets/images/component/bt_orig/comp_pepssi_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/bt_orig/comp_pepssi_hover.png", "assets/images/component/bt_orig/comp_pepssi_hover.png");
			type.set ("assets/images/component/bt_orig/comp_pepssi_hover.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/bt_orig/comp_ralph_alt.png", "assets/images/component/bt_orig/comp_ralph_alt.png");
			type.set ("assets/images/component/bt_orig/comp_ralph_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/bt_orig/comp_ralph_hover.png", "assets/images/component/bt_orig/comp_ralph_hover.png");
			type.set ("assets/images/component/bt_orig/comp_ralph_hover.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_alice_alt.png", "assets/images/component/buttonsprites/comp_alice_alt.png");
			type.set ("assets/images/component/buttonsprites/comp_alice_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_alice_d.png", "assets/images/component/buttonsprites/comp_alice_d.png");
			type.set ("assets/images/component/buttonsprites/comp_alice_d.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_heat_alt.png", "assets/images/component/buttonsprites/comp_heat_alt.png");
			type.set ("assets/images/component/buttonsprites/comp_heat_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_heat_d.png", "assets/images/component/buttonsprites/comp_heat_d.png");
			type.set ("assets/images/component/buttonsprites/comp_heat_d.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_lorri_alt.png", "assets/images/component/buttonsprites/comp_lorri_alt.png");
			type.set ("assets/images/component/buttonsprites/comp_lorri_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_lorri_d.png", "assets/images/component/buttonsprites/comp_lorri_d.png");
			type.set ("assets/images/component/buttonsprites/comp_lorri_d.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_pepssi_alt.png", "assets/images/component/buttonsprites/comp_pepssi_alt.png");
			type.set ("assets/images/component/buttonsprites/comp_pepssi_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_pepssi_d.png", "assets/images/component/buttonsprites/comp_pepssi_d.png");
			type.set ("assets/images/component/buttonsprites/comp_pepssi_d.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_ralph_alt.png", "assets/images/component/buttonsprites/comp_ralph_alt.png");
			type.set ("assets/images/component/buttonsprites/comp_ralph_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_ralph_d.png", "assets/images/component/buttonsprites/comp_ralph_d.png");
			type.set ("assets/images/component/buttonsprites/comp_ralph_d.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_rex_alt.png", "assets/images/component/buttonsprites/comp_rex_alt.png");
			type.set ("assets/images/component/buttonsprites/comp_rex_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_rex_d.png", "assets/images/component/buttonsprites/comp_rex_d.png");
			type.set ("assets/images/component/buttonsprites/comp_rex_d.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_rtg_alt.png", "assets/images/component/buttonsprites/comp_rtg_alt.png");
			type.set ("assets/images/component/buttonsprites/comp_rtg_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_rtg_d.png", "assets/images/component/buttonsprites/comp_rtg_d.png");
			type.set ("assets/images/component/buttonsprites/comp_rtg_d.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_swap_alt.png", "assets/images/component/buttonsprites/comp_swap_alt.png");
			type.set ("assets/images/component/buttonsprites/comp_swap_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/comp_swap_d.png", "assets/images/component/buttonsprites/comp_swap_d.png");
			type.set ("assets/images/component/buttonsprites/comp_swap_d.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/buttonsprites/template.pdn", "assets/images/component/buttonsprites/template.pdn");
			type.set ("assets/images/component/buttonsprites/template.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/component/comp_alice.png", "assets/images/component/comp_alice.png");
			type.set ("assets/images/component/comp_alice.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/comp_heatshield.png", "assets/images/component/comp_heatshield.png");
			type.set ("assets/images/component/comp_heatshield.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/comp_lorri.png", "assets/images/component/comp_lorri.png");
			type.set ("assets/images/component/comp_lorri.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/comp_pepssi.png", "assets/images/component/comp_pepssi.png");
			type.set ("assets/images/component/comp_pepssi.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/comp_ralph.png", "assets/images/component/comp_ralph.png");
			type.set ("assets/images/component/comp_ralph.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/comp_rex.png", "assets/images/component/comp_rex.png");
			type.set ("assets/images/component/comp_rex.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/comp_rtg.png", "assets/images/component/comp_rtg.png");
			type.set ("assets/images/component/comp_rtg.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/comp_swap.png", "assets/images/component/comp_swap.png");
			type.set ("assets/images/component/comp_swap.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/NH.png", "assets/images/component/NH.png");
			type.set ("assets/images/component/NH.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/component/nh_large.png", "assets/images/component/nh_large.png");
			type.set ("assets/images/component/nh_large.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/facts/earth-32x.png", "assets/images/facts/earth-32x.png");
			type.set ("assets/images/facts/earth-32x.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/facts/fact0.png", "assets/images/facts/fact0.png");
			type.set ("assets/images/facts/fact0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/facts/fact1.png", "assets/images/facts/fact1.png");
			type.set ("assets/images/facts/fact1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/facts/fact2.png", "assets/images/facts/fact2.png");
			type.set ("assets/images/facts/fact2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/facts/fact3.png", "assets/images/facts/fact3.png");
			type.set ("assets/images/facts/fact3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/facts/facthide.png", "assets/images/facts/facthide.png");
			type.set ("assets/images/facts/facthide.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/found/alicefound.pdn", "assets/images/found/alicefound.pdn");
			type.set ("assets/images/found/alicefound.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/found/alicefound.png", "assets/images/found/alicefound.png");
			type.set ("assets/images/found/alicefound.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/found/alice_button_backdrop.png", "assets/images/found/alice_button_backdrop.png");
			type.set ("assets/images/found/alice_button_backdrop.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/found/found-template.pdn", "assets/images/found/found-template.pdn");
			type.set ("assets/images/found/found-template.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/found/found_alice.png", "assets/images/found/found_alice.png");
			type.set ("assets/images/found/found_alice.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/found/found_alice_button.pdn", "assets/images/found/found_alice_button.pdn");
			type.set ("assets/images/found/found_alice_button.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/found/found_alice_button.png", "assets/images/found/found_alice_button.png");
			type.set ("assets/images/found/found_alice_button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/found/found_pepssi.png", "assets/images/found/found_pepssi.png");
			type.set ("assets/images/found/found_pepssi.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/found/found_pepssi_button.png", "assets/images/found/found_pepssi_button.png");
			type.set ("assets/images/found/found_pepssi_button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/found/rtg_found.pdn", "assets/images/found/rtg_found.pdn");
			type.set ("assets/images/found/rtg_found.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/hub/alice_info.png", "assets/images/hub/alice_info.png");
			type.set ("assets/images/hub/alice_info.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hub/blockout.png", "assets/images/hub/blockout.png");
			type.set ("assets/images/hub/blockout.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hub/components_hero.png", "assets/images/hub/components_hero.png");
			type.set ("assets/images/hub/components_hero.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hub/heat_info.png", "assets/images/hub/heat_info.png");
			type.set ("assets/images/hub/heat_info.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hub/lorri_info.png", "assets/images/hub/lorri_info.png");
			type.set ("assets/images/hub/lorri_info.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hub/pepssi_info.png", "assets/images/hub/pepssi_info.png");
			type.set ("assets/images/hub/pepssi_info.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hub/ralph_info.png", "assets/images/hub/ralph_info.png");
			type.set ("assets/images/hub/ralph_info.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hub/rex_info.png", "assets/images/hub/rex_info.png");
			type.set ("assets/images/hub/rex_info.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hub/rtg_info.png", "assets/images/hub/rtg_info.png");
			type.set ("assets/images/hub/rtg_info.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hub/swap_info.png", "assets/images/hub/swap_info.png");
			type.set ("assets/images/hub/swap_info.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/icon.ico", "assets/images/icon.ico");
			type.set ("assets/images/icon.ico", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/intro/beach.png", "assets/images/intro/beach.png");
			type.set ("assets/images/intro/beach.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/intro/name.png", "assets/images/intro/name.png");
			type.set ("assets/images/intro/name.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/intro/original/beach.pdn", "assets/images/intro/original/beach.pdn");
			type.set ("assets/images/intro/original/beach.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/intro/original/Untitled.pdn", "assets/images/intro/original/Untitled.pdn");
			type.set ("assets/images/intro/original/Untitled.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/intro/original/vab.pdn", "assets/images/intro/original/vab.pdn");
			type.set ("assets/images/intro/original/vab.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/intro/plane.png", "assets/images/intro/plane.png");
			type.set ("assets/images/intro/plane.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/intro/text0.png", "assets/images/intro/text0.png");
			type.set ("assets/images/intro/text0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/intro/text1.png", "assets/images/intro/text1.png");
			type.set ("assets/images/intro/text1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/intro/text2.png", "assets/images/intro/text2.png");
			type.set ("assets/images/intro/text2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/intro/text3.png", "assets/images/intro/text3.png");
			type.set ("assets/images/intro/text3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/intro/tower.png", "assets/images/intro/tower.png");
			type.set ("assets/images/intro/tower.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/intro/vab.png", "assets/images/intro/vab.png");
			type.set ("assets/images/intro/vab.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/cloud0.png", "assets/images/launchblock/cloud0.png");
			type.set ("assets/images/launchblock/cloud0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/cloud1.png", "assets/images/launchblock/cloud1.png");
			type.set ("assets/images/launchblock/cloud1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/launch-thin-window.png", "assets/images/launchblock/launch-thin-window.png");
			type.set ("assets/images/launchblock/launch-thin-window.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/launch-thin-window.png.meta", "assets/images/launchblock/launch-thin-window.png.meta");
			type.set ("assets/images/launchblock/launch-thin-window.png.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-atlas-v.pdn.meta", "assets/images/launchblock/nh-atlas-v.pdn.meta");
			type.set ("assets/images/launchblock/nh-atlas-v.pdn.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-launch-block.pdn.meta", "assets/images/launchblock/nh-launch-block.pdn.meta");
			type.set ("assets/images/launchblock/nh-launch-block.pdn.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-launch-block.png.meta", "assets/images/launchblock/nh-launch-block.png.meta");
			type.set ("assets/images/launchblock/nh-launch-block.png.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-launch-long - Copy.pdn.meta", "assets/images/launchblock/nh-launch-long - Copy.pdn.meta");
			type.set ("assets/images/launchblock/nh-launch-long - Copy.pdn.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-launch-long-old.pdn.meta", "assets/images/launchblock/nh-launch-long-old.pdn.meta");
			type.set ("assets/images/launchblock/nh-launch-long-old.pdn.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-launch-long.pdn.meta", "assets/images/launchblock/nh-launch-long.pdn.meta");
			type.set ("assets/images/launchblock/nh-launch-long.pdn.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-launch-long.png.meta", "assets/images/launchblock/nh-launch-long.png.meta");
			type.set ("assets/images/launchblock/nh-launch-long.png.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-pastel.png.meta", "assets/images/launchblock/nh-pastel.png.meta");
			type.set ("assets/images/launchblock/nh-pastel.png.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-postcard - Copy - Copy.png.meta", "assets/images/launchblock/nh-postcard - Copy - Copy.png.meta");
			type.set ("assets/images/launchblock/nh-postcard - Copy - Copy.png.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-postcard - Copy.pdn.meta", "assets/images/launchblock/nh-postcard - Copy.pdn.meta");
			type.set ("assets/images/launchblock/nh-postcard - Copy.pdn.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-postcard - Copy.png.meta", "assets/images/launchblock/nh-postcard - Copy.png.meta");
			type.set ("assets/images/launchblock/nh-postcard - Copy.png.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-postcard-skeu.png.meta", "assets/images/launchblock/nh-postcard-skeu.png.meta");
			type.set ("assets/images/launchblock/nh-postcard-skeu.png.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-postcard.pdn.meta", "assets/images/launchblock/nh-postcard.pdn.meta");
			type.set ("assets/images/launchblock/nh-postcard.pdn.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/nh-postcard.png.meta", "assets/images/launchblock/nh-postcard.png.meta");
			type.set ("assets/images/launchblock/nh-postcard.png.meta", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-atlas-v.pdn", "assets/images/launchblock/other/nh-atlas-v.pdn");
			type.set ("assets/images/launchblock/other/nh-atlas-v.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-launch-block/Atlas_V_551_with_New_Horizons_on_Launch_Pad_41.jpg", "assets/images/launchblock/other/nh-launch-block/Atlas_V_551_with_New_Horizons_on_Launch_Pad_41.jpg");
			type.set ("assets/images/launchblock/other/nh-launch-block/Atlas_V_551_with_New_Horizons_on_Launch_Pad_41.jpg", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-launch-block/nh-static-atlasv-launch.jpg", "assets/images/launchblock/other/nh-launch-block/nh-static-atlasv-launch.jpg");
			type.set ("assets/images/launchblock/other/nh-launch-block/nh-static-atlasv-launch.jpg", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-launch-block.pdn", "assets/images/launchblock/other/nh-launch-block.pdn");
			type.set ("assets/images/launchblock/other/nh-launch-block.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-launch-block.png", "assets/images/launchblock/other/nh-launch-block.png");
			type.set ("assets/images/launchblock/other/nh-launch-block.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-launch-long - Copy.pdn", "assets/images/launchblock/other/nh-launch-long - Copy.pdn");
			type.set ("assets/images/launchblock/other/nh-launch-long - Copy.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-launch-long-old.pdn", "assets/images/launchblock/other/nh-launch-long-old.pdn");
			type.set ("assets/images/launchblock/other/nh-launch-long-old.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-launch-long.pdn", "assets/images/launchblock/other/nh-launch-long.pdn");
			type.set ("assets/images/launchblock/other/nh-launch-long.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-launch-long.png", "assets/images/launchblock/other/nh-launch-long.png");
			type.set ("assets/images/launchblock/other/nh-launch-long.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-pastel.png", "assets/images/launchblock/other/nh-pastel.png");
			type.set ("assets/images/launchblock/other/nh-pastel.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-postcard - Copy.pdn", "assets/images/launchblock/other/nh-postcard - Copy.pdn");
			type.set ("assets/images/launchblock/other/nh-postcard - Copy.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-postcard - Copy.png", "assets/images/launchblock/other/nh-postcard - Copy.png");
			type.set ("assets/images/launchblock/other/nh-postcard - Copy.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-postcard.pdn", "assets/images/launchblock/other/nh-postcard.pdn");
			type.set ("assets/images/launchblock/other/nh-postcard.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/other/nh-postcard.png", "assets/images/launchblock/other/nh-postcard.png");
			type.set ("assets/images/launchblock/other/nh-postcard.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/other/pad-norocket.pdn", "assets/images/launchblock/other/pad-norocket.pdn");
			type.set ("assets/images/launchblock/other/pad-norocket.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/other/pad-rocket.pdn", "assets/images/launchblock/other/pad-rocket.pdn");
			type.set ("assets/images/launchblock/other/pad-rocket.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/launchblock/pad-norocket.png", "assets/images/launchblock/pad-norocket.png");
			type.set ("assets/images/launchblock/pad-norocket.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/pad-rocket.png", "assets/images/launchblock/pad-rocket.png");
			type.set ("assets/images/launchblock/pad-rocket.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/skyback - Copy.png", "assets/images/launchblock/skyback - Copy.png");
			type.set ("assets/images/launchblock/skyback - Copy.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/launchblock/skyback.png", "assets/images/launchblock/skyback.png");
			type.set ("assets/images/launchblock/skyback.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/logo.png", "assets/images/logo.png");
			type.set ("assets/images/logo.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/logoflicker.png", "assets/images/logoflicker.png");
			type.set ("assets/images/logoflicker.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button originals/buttontemplate - Copy.pdn", "assets/images/menu/button originals/buttontemplate - Copy.pdn");
			type.set ("assets/images/menu/button originals/buttontemplate - Copy.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/menu/button originals/button_begin.pdn", "assets/images/menu/button originals/button_begin.pdn");
			type.set ("assets/images/menu/button originals/button_begin.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/menu/button originals/button_mute.pdn", "assets/images/menu/button originals/button_mute.pdn");
			type.set ("assets/images/menu/button originals/button_mute.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/menu/button originals/button_pad.pdn", "assets/images/menu/button originals/button_pad.pdn");
			type.set ("assets/images/menu/button originals/button_pad.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/menu/button originals/button_quit.pdn", "assets/images/menu/button originals/button_quit.pdn");
			type.set ("assets/images/menu/button originals/button_quit.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/menu/button originals/button_settings.pdn", "assets/images/menu/button originals/button_settings.pdn");
			type.set ("assets/images/menu/button originals/button_settings.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/menu/button originals/d_warning.pdn", "assets/images/menu/button originals/d_warning.pdn");
			type.set ("assets/images/menu/button originals/d_warning.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/menu/buttontemplate.pdn", "assets/images/menu/buttontemplate.pdn");
			type.set ("assets/images/menu/buttontemplate.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/menu/button_about.png", "assets/images/menu/button_about.png");
			type.set ("assets/images/menu/button_about.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_back.png", "assets/images/menu/button_back.png");
			type.set ("assets/images/menu/button_back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_begin.png", "assets/images/menu/button_begin.png");
			type.set ("assets/images/menu/button_begin.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_debug.png", "assets/images/menu/button_debug.png");
			type.set ("assets/images/menu/button_debug.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_f.png", "assets/images/menu/button_f.png");
			type.set ("assets/images/menu/button_f.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_facts.png", "assets/images/menu/button_facts.png");
			type.set ("assets/images/menu/button_facts.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_full.png", "assets/images/menu/button_full.png");
			type.set ("assets/images/menu/button_full.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_pad.png", "assets/images/menu/button_pad.png");
			type.set ("assets/images/menu/button_pad.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_pluto.png", "assets/images/menu/button_pluto.png");
			type.set ("assets/images/menu/button_pluto.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_quit.png", "assets/images/menu/button_quit.png");
			type.set ("assets/images/menu/button_quit.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_rand.png", "assets/images/menu/button_rand.png");
			type.set ("assets/images/menu/button_rand.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_setting.png", "assets/images/menu/button_setting.png");
			type.set ("assets/images/menu/button_setting.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/button_settings.png", "assets/images/menu/button_settings.png");
			type.set ("assets/images/menu/button_settings.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/coordsblock.png", "assets/images/menu/coordsblock.png");
			type.set ("assets/images/menu/coordsblock.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/d_warning.png", "assets/images/menu/d_warning.png");
			type.set ("assets/images/menu/d_warning.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/d_warn_cancel.png", "assets/images/menu/d_warn_cancel.png");
			type.set ("assets/images/menu/d_warn_cancel.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/d_warn_ok.pdn", "assets/images/menu/d_warn_ok.pdn");
			type.set ("assets/images/menu/d_warn_ok.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/menu/d_warn_ok.png", "assets/images/menu/d_warn_ok.png");
			type.set ("assets/images/menu/d_warn_ok.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/full_exit_notice.png", "assets/images/menu/full_exit_notice.png");
			type.set ("assets/images/menu/full_exit_notice.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/CharonOrbit.png", "assets/images/menu/moons/CharonOrbit.png");
			type.set ("assets/images/menu/moons/CharonOrbit.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/HydraOrbit.png", "assets/images/menu/moons/HydraOrbit.png");
			type.set ("assets/images/menu/moons/HydraOrbit.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/KerberosOrbit.png", "assets/images/menu/moons/KerberosOrbit.png");
			type.set ("assets/images/menu/moons/KerberosOrbit.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/NixOrbit.png", "assets/images/menu/moons/NixOrbit.png");
			type.set ("assets/images/menu/moons/NixOrbit.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/original/Charon.png", "assets/images/menu/moons/original/Charon.png");
			type.set ("assets/images/menu/moons/original/Charon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/original/Hydra.png", "assets/images/menu/moons/original/Hydra.png");
			type.set ("assets/images/menu/moons/original/Hydra.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/original/Kerberos.png", "assets/images/menu/moons/original/Kerberos.png");
			type.set ("assets/images/menu/moons/original/Kerberos.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/original/Nix.png", "assets/images/menu/moons/original/Nix.png");
			type.set ("assets/images/menu/moons/original/Nix.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/original/Styx.png", "assets/images/menu/moons/original/Styx.png");
			type.set ("assets/images/menu/moons/original/Styx.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/Pluto.png", "assets/images/menu/moons/Pluto.png");
			type.set ("assets/images/menu/moons/Pluto.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/moons/StyxOrbit.png", "assets/images/menu/moons/StyxOrbit.png");
			type.set ("assets/images/menu/moons/StyxOrbit.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/splash/splash_x640.jpg", "assets/images/menu/splash/splash_x640.jpg");
			type.set ("assets/images/menu/splash/splash_x640.jpg", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/splash/startup-splash-hero - Copy.png", "assets/images/menu/splash/startup-splash-hero - Copy.png");
			type.set ("assets/images/menu/splash/startup-splash-hero - Copy.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/splash/startup-splash-hero.png", "assets/images/menu/splash/startup-splash-hero.png");
			type.set ("assets/images/menu/splash/startup-splash-hero.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/splash_x640.png", "assets/images/menu/splash_x640.png");
			type.set ("assets/images/menu/splash_x640.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/starback.png", "assets/images/menu/starback.png");
			type.set ("assets/images/menu/starback.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/menu/tutorial.png", "assets/images/menu/tutorial.png");
			type.set ("assets/images/menu/tutorial.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/misc/320xp.pdn", "assets/images/misc/320xp.pdn");
			type.set ("assets/images/misc/320xp.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/misc/320xp.png", "assets/images/misc/320xp.png");
			type.set ("assets/images/misc/320xp.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/misc/pls.png", "assets/images/misc/pls.png");
			type.set ("assets/images/misc/pls.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/mute/Mute.png", "assets/images/mute/Mute.png");
			type.set ("assets/images/mute/Mute.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/mute/MuteOn.png", "assets/images/mute/MuteOn.png");
			type.set ("assets/images/mute/MuteOn.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/background.png", "assets/images/pepssiwire/background.png");
			type.set ("assets/images/pepssiwire/background.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/bblue.png", "assets/images/pepssiwire/bblue.png");
			type.set ("assets/images/pepssiwire/bblue.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/box - Copy.pdn", "assets/images/pepssiwire/box - Copy.pdn");
			type.set ("assets/images/pepssiwire/box - Copy.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/pepssiwire/box-mockup.pdn", "assets/images/pepssiwire/box-mockup.pdn");
			type.set ("assets/images/pepssiwire/box-mockup.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/pepssiwire/box-mockup.png", "assets/images/pepssiwire/box-mockup.png");
			type.set ("assets/images/pepssiwire/box-mockup.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/box.pdn", "assets/images/pepssiwire/box.pdn");
			type.set ("assets/images/pepssiwire/box.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/pepssiwire/box.png", "assets/images/pepssiwire/box.png");
			type.set ("assets/images/pepssiwire/box.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/bparcel.png", "assets/images/pepssiwire/bparcel.png");
			type.set ("assets/images/pepssiwire/bparcel.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/bpeach.png", "assets/images/pepssiwire/bpeach.png");
			type.set ("assets/images/pepssiwire/bpeach.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/bpink.png", "assets/images/pepssiwire/bpink.png");
			type.set ("assets/images/pepssiwire/bpink.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/colors.png", "assets/images/pepssiwire/colors.png");
			type.set ("assets/images/pepssiwire/colors.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/dialogback.png", "assets/images/pepssiwire/dialogback.png");
			type.set ("assets/images/pepssiwire/dialogback.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/dialogtext.png", "assets/images/pepssiwire/dialogtext.png");
			type.set ("assets/images/pepssiwire/dialogtext.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/old/0bluealt.png", "assets/images/pepssiwire/old/0bluealt.png");
			type.set ("assets/images/pepssiwire/old/0bluealt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/old/0limealt.png", "assets/images/pepssiwire/old/0limealt.png");
			type.set ("assets/images/pepssiwire/old/0limealt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/old/0peachalt.png", "assets/images/pepssiwire/old/0peachalt.png");
			type.set ("assets/images/pepssiwire/old/0peachalt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/old/0pinkalt.png", "assets/images/pepssiwire/old/0pinkalt.png");
			type.set ("assets/images/pepssiwire/old/0pinkalt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/old/1bluealt.png", "assets/images/pepssiwire/old/1bluealt.png");
			type.set ("assets/images/pepssiwire/old/1bluealt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/old/1limealt.png", "assets/images/pepssiwire/old/1limealt.png");
			type.set ("assets/images/pepssiwire/old/1limealt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/old/1peachalt.png", "assets/images/pepssiwire/old/1peachalt.png");
			type.set ("assets/images/pepssiwire/old/1peachalt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/old/1pinkalt.png", "assets/images/pepssiwire/old/1pinkalt.png");
			type.set ("assets/images/pepssiwire/old/1pinkalt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/original/0blue.png", "assets/images/pepssiwire/original/0blue.png");
			type.set ("assets/images/pepssiwire/original/0blue.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/original/0lime.png", "assets/images/pepssiwire/original/0lime.png");
			type.set ("assets/images/pepssiwire/original/0lime.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/original/0peach.png", "assets/images/pepssiwire/original/0peach.png");
			type.set ("assets/images/pepssiwire/original/0peach.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/original/0pink.png", "assets/images/pepssiwire/original/0pink.png");
			type.set ("assets/images/pepssiwire/original/0pink.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/parcel.pdn", "assets/images/pepssiwire/parcel.pdn");
			type.set ("assets/images/pepssiwire/parcel.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/pepssiwire/parcel.png", "assets/images/pepssiwire/parcel.png");
			type.set ("assets/images/pepssiwire/parcel.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pepssiwire/sgsgsg.pdn", "assets/images/pepssiwire/sgsgsg.pdn");
			type.set ("assets/images/pepssiwire/sgsgsg.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/pepssiwire/Untitled.pdn", "assets/images/pepssiwire/Untitled.pdn");
			type.set ("assets/images/pepssiwire/Untitled.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/pepssiwire/Untitled.png", "assets/images/pepssiwire/Untitled.png");
			type.set ("assets/images/pepssiwire/Untitled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/reference.txt", "assets/images/reference.txt");
			type.set ("assets/images/reference.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/rtgrun/background.pdn", "assets/images/rtgrun/background.pdn");
			type.set ("assets/images/rtgrun/background.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/rtgrun/background.png", "assets/images/rtgrun/background.png");
			type.set ("assets/images/rtgrun/background.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/rtgrun/clouds.png", "assets/images/rtgrun/clouds.png");
			type.set ("assets/images/rtgrun/clouds.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/rtgrun/mockup.pdn", "assets/images/rtgrun/mockup.pdn");
			type.set ("assets/images/rtgrun/mockup.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/rtgrun/placeholder.pdn", "assets/images/rtgrun/placeholder.pdn");
			type.set ("assets/images/rtgrun/placeholder.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/rtgrun/placeholder.png", "assets/images/rtgrun/placeholder.png");
			type.set ("assets/images/rtgrun/placeholder.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/rtgrun/sky.png", "assets/images/rtgrun/sky.png");
			type.set ("assets/images/rtgrun/sky.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/settings/button_fullscreen.png", "assets/images/settings/button_fullscreen.png");
			type.set ("assets/images/settings/button_fullscreen.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/settings/button_fullscreen_alt.png", "assets/images/settings/button_fullscreen_alt.png");
			type.set ("assets/images/settings/button_fullscreen_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/settings/button_sound.png", "assets/images/settings/button_sound.png");
			type.set ("assets/images/settings/button_sound.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/settings/button_sound_alt.png", "assets/images/settings/button_sound_alt.png");
			type.set ("assets/images/settings/button_sound_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/settings/originals/button_fullscreen.pdn", "assets/images/settings/originals/button_fullscreen.pdn");
			type.set ("assets/images/settings/originals/button_fullscreen.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/settings/originals/button_sound.pdn", "assets/images/settings/originals/button_sound.pdn");
			type.set ("assets/images/settings/originals/button_sound.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/settings/title_settings.png", "assets/images/settings/title_settings.png");
			type.set ("assets/images/settings/title_settings.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/music/menu-main2.wav", "assets/music/menu-main2.wav");
			type.set ("assets/music/menu-main2.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/music/music_credits.txt", "assets/music/music_credits.txt");
			type.set ("assets/music/music_credits.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/data.wav", "assets/sounds/data.wav");
			type.set ("assets/sounds/data.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/error.wav", "assets/sounds/error.wav");
			type.set ("assets/sounds/error.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/get.wav", "assets/sounds/get.wav");
			type.set ("assets/sounds/get.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/introtone.mp3", "assets/sounds/introtone.mp3");
			type.set ("assets/sounds/introtone.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/introtone.wav", "assets/sounds/introtone.wav");
			type.set ("assets/sounds/introtone.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Pickup_Coin.wav", "assets/sounds/Pickup_Coin.wav");
			type.set ("assets/sounds/Pickup_Coin.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/select.wav", "assets/sounds/select.wav");
			type.set ("assets/sounds/select.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/signal.wav", "assets/sounds/signal.wav");
			type.set ("assets/sounds/signal.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/beep.ogg", "assets/sounds/beep.ogg");
			type.set ("assets/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/flixel.ogg", "assets/sounds/flixel.ogg");
			type.set ("assets/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/fonts/nokiafc22.ttf", "assets/fonts/nokiafc22.ttf");
			type.set ("assets/fonts/nokiafc22.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/arial.ttf", "assets/fonts/arial.ttf");
			type.set ("assets/fonts/arial.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
